import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gql, useQuery } from '@apollo/client'
import pokemonAPI from '../apollo-client'
import Login from './components/login'

export async function getServerSideProps({res}){
  
  const limit = 251
  const offset = 1

  const { data } = await pokemonAPI.query({
    query: gql`
      query pokemons($limit: Int, $offset: Int) {
        pokemons(limit: $limit, offset: $offset) {
          count
          next
          previous
          status
          message
          results {
            url
            name
            image
          }
        }
      }
    `
  })

  return {
    props: {
      resultPokemon: data.pokemons,
    }
  };
}

export default function Home({ resultPokemon }) {
  console.log(resultPokemon)
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div>
        {/* <ul>
          {
            resultPokemon.results.map((pokemon) => (
              <li key={pokemon.name}>{pokemon.name}</li>
            ))
          }
        </ul> */}
        <Login />
      </div>
    </>
  )
}
